language: scala
matrix:
  include:
    - scala: 2.12.11
      jdk: openjdk8
    - scala: 2.12.11
      jdk: openjdk11
    - scala: 2.13.2
      jdk: openjdk8
    - scala: 2.13.2
      jdk: openjdk11

    - name: scalafmt
      scala: 2.13.2
      jdk: openjdk11
      script: sbt ++$TRAVIS_SCALA_VERSION clean scalafmtSbtCheck scalafmtCheck test:scalafmtCheck

    - name: coverage
      scala: 2.13.2
      jdk: openjdk11
      script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport coverageAggregate
      after_success: bash <(curl -s https://codecov.io/bash)

    - name: avro
      scala: 2.13.1
      jdk: openjdk11
      script: sbt ++$TRAVIS_SCALA_VERSION -Davro.version=1.8.2 clean avro/test

before_cache:
  # Tricks to avoid unnecessary cache updates
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test

notifications:
  email:
    - flatmap-squad@spotify.com
